// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package greeter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

///////////////////////////////------------------my test -------------------------------------//////////////////////////
// 枚举
type Color int32

const (
	Color_RED    Color = 0
	Color_YELLOW Color = 1
	Color_WHITE  Color = 2
	Color_BLACK  Color = 3
)

var Color_name = map[int32]string{
	0: "RED",
	1: "YELLOW",
	2: "WHITE",
	3: "BLACK",
}

var Color_value = map[string]int32{
	"RED":    0,
	"YELLOW": 1,
	"WHITE":  2,
	"BLACK":  3,
}

func (x Color) String() string {
	return proto.EnumName(Color_name, int32(x))
}

func (Color) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

// message 用于数据结构定义
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type MyInfo struct {
	// 使用 protobuf 的整个想法是，它允许您添加/删除协议定义中的字段，
	// 同时仍然完全向前/向后兼容较新/较旧的二进制文件。 >required 字段打破了这一点。
	// required string name = 1;
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 如果你想在它的父消息类型的外部重用这个消息类型，你需要以Parent.Type的形式使用它
	// MyInfo.body bo = 2;
	Bo                   *MyInfoBody `protobuf:"bytes,2,opt,name=bo,proto3" json:"bo,omitempty"`
	Color                Color       `protobuf:"varint,3,opt,name=color,proto3,enum=Color" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MyInfo) Reset()         { *m = MyInfo{} }
func (m *MyInfo) String() string { return proto.CompactTextString(m) }
func (*MyInfo) ProtoMessage()    {}
func (*MyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{2}
}

func (m *MyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyInfo.Unmarshal(m, b)
}
func (m *MyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyInfo.Marshal(b, m, deterministic)
}
func (m *MyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyInfo.Merge(m, src)
}
func (m *MyInfo) XXX_Size() int {
	return xxx_messageInfo_MyInfo.Size(m)
}
func (m *MyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MyInfo proto.InternalMessageInfo

func (m *MyInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MyInfo) GetBo() *MyInfoBody {
	if m != nil {
		return m.Bo
	}
	return nil
}

func (m *MyInfo) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_RED
}

// 允许嵌套定义
type MyInfoBody struct {
	Length               int32    `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Weight               int32    `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyInfoBody) Reset()         { *m = MyInfoBody{} }
func (m *MyInfoBody) String() string { return proto.CompactTextString(m) }
func (*MyInfoBody) ProtoMessage()    {}
func (*MyInfoBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{2, 0}
}

func (m *MyInfoBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyInfoBody.Unmarshal(m, b)
}
func (m *MyInfoBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyInfoBody.Marshal(b, m, deterministic)
}
func (m *MyInfoBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyInfoBody.Merge(m, src)
}
func (m *MyInfoBody) XXX_Size() int {
	return xxx_messageInfo_MyInfoBody.Size(m)
}
func (m *MyInfoBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MyInfoBody.DiscardUnknown(m)
}

var xxx_messageInfo_MyInfoBody proto.InternalMessageInfo

func (m *MyInfoBody) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *MyInfoBody) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("Color", Color_name, Color_value)
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*MyInfo)(nil), "MyInfo")
	proto.RegisterType((*MyInfoBody)(nil), "MyInfo.body")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0xb4, 0xbb, 0xb1, 0x63, 0x5b, 0xc2, 0x1e, 0xa4, 0x84, 0x1e, 0xca, 0x9e, 0xa2,
	0xc2, 0x1e, 0x52, 0xf0, 0xae, 0x35, 0xb4, 0xc5, 0x14, 0x61, 0x15, 0x8a, 0x47, 0x53, 0xc7, 0x34,
	0x90, 0x66, 0x63, 0xb2, 0x2a, 0x79, 0x0b, 0x1f, 0x59, 0xb2, 0x09, 0xa2, 0xe0, 0x6d, 0xfe, 0xe1,
	0xcf, 0x47, 0xe6, 0x5b, 0x18, 0x27, 0x25, 0xa2, 0xc6, 0x52, 0x14, 0xa5, 0xd2, 0x8a, 0x73, 0x18,
	0xad, 0x31, 0xcb, 0x94, 0xc4, 0xb7, 0x77, 0xac, 0x34, 0x63, 0x30, 0xc8, 0x9f, 0x8f, 0x38, 0xb5,
	0xe6, 0x96, 0x3f, 0x94, 0x66, 0xe6, 0x97, 0x30, 0xee, 0x3a, 0x55, 0xa1, 0xf2, 0x0a, 0x99, 0x07,
	0x27, 0x86, 0x92, 0xe6, 0xc9, 0xd4, 0x36, 0xc5, 0x9f, 0xcc, 0xbf, 0x2c, 0xa0, 0xdb, 0x7a, 0x93,
	0xbf, 0xaa, 0xff, 0x58, 0x6c, 0x06, 0x76, 0xac, 0xcc, 0x47, 0xa7, 0xc1, 0x48, 0xb4, 0x45, 0x11,
	0xab, 0x97, 0x5a, 0xda, 0xb1, 0x62, 0x33, 0x20, 0x7b, 0x95, 0xa9, 0x72, 0xda, 0x9f, 0x5b, 0xfe,
	0x24, 0xa0, 0x62, 0xd9, 0x24, 0xd9, 0x2e, 0xbd, 0x2b, 0x18, 0x34, 0x4d, 0x76, 0x06, 0x34, 0xc3,
	0x3c, 0xd1, 0x07, 0x43, 0x26, 0xb2, 0x4b, 0xcd, 0xfe, 0x13, 0xd3, 0xe4, 0xa0, 0x0d, 0x9f, 0xc8,
	0x2e, 0x71, 0x07, 0x48, 0x78, 0x2c, 0x74, 0x7d, 0x11, 0x00, 0x31, 0x40, 0xe6, 0x40, 0x5f, 0x86,
	0xb7, 0x6e, 0x8f, 0x01, 0xd0, 0xa7, 0x30, 0x8a, 0xee, 0x77, 0xae, 0xc5, 0x86, 0x40, 0x76, 0xeb,
	0xcd, 0x63, 0xe8, 0xda, 0xcd, 0x78, 0x13, 0x5d, 0x2f, 0xef, 0xdc, 0x7e, 0xb0, 0x00, 0x67, 0xd5,
	0x1a, 0x63, 0x3e, 0x10, 0xe3, 0x81, 0x8d, 0xc5, 0x6f, 0x67, 0xde, 0x44, 0xfc, 0xd1, 0xc3, 0x7b,
	0xc1, 0x39, 0x0c, 0xb7, 0xf5, 0x03, 0x96, 0x1f, 0xe9, 0xbe, 0x39, 0xd9, 0x59, 0xa1, 0x36, 0x46,
	0xa8, 0x30, 0x3f, 0xe2, 0x39, 0xdd, 0xe5, 0xbc, 0x17, 0x53, 0xf3, 0x0e, 0x8b, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x72, 0xfd, 0x9e, 0x9e, 0x98, 0x01, 0x00, 0x00,
}
